### ISSUE TITLE
Password for database

### ISSUE THREAD

**Issue by leobr2014** [evermind/docker-froxlor#2]
The password in the values.yaml file does not work.

Thanks

Leobr

**Comment by micw** [comment]
Please elaborate in detail.
You need to create your own values with the settings you like to overwrite (including mysql password and rootPassword. Then later in froxlor setup you can use these passwords.
Ensure that you use the correct host name (which is the service name of the mysql service in k8s).

**Comment by micw** [comment]
FYI, I added a "NOTES.txt" to the chart that prints the required steps after deployment

**Comment by tgruenert** [comment]
closed because no more feedback from thread owner
